const HOUSES = [
{id:"h01",tier:1,name:"The Blue House",ref:"Tao Plus VU 0451 · Rep C09928RL",area:"El Álamo, Madrid",
 verdict:"First choice, and it has been since the first day of scouting. Blue American cladding, ivy across the whole front, a full-width porch, and a pool with a shaded pergola behind it. The only house on the list that already looks like the video without us doing anything to it.",
 note:"Listed by two different agencies. Same house. Book through whichever one quotes lower.",
 links:[["Tao Plus","https://www.taoplus.es/propiedades/vivienda-unifamiliar-0451/"],["Rep Locations","https://replocations.com/localizaciones/c09928rl/"]],
 shots:5},
{id:"h02",tier:2,name:"The Prefab",ref:"Rep C10244BRL",area:"Guadarrama, Madrid",
 verdict:"The exterior is the single strongest image we have found anywhere. Wooden American front, porch, open meadow behind. The problem is inside: one open room and nothing else, so the house cannot carry a whole video by itself.",
 blocker:"Two conditions before this is viable. The day rate has to be low, and a second element has to be locked in first, a caravan or an American truck. Without that second element there is not enough here to shoot.",
 links:[["Rep Locations","https://replocations.com/localizaciones/c10244brl/"]],
 shots:4},
{id:"h03",tier:3,name:"The Wood House",ref:"Tao Plus VU 0236",area:"Urb. Santo Domingo, Madrid",
 verdict:"Strong candidate. Beautiful front under the pines, and a separate wooden garage on the far side of the plot that gives us a real second setup inside the same booking. Pool, pergola, and a porch running the full width of the house.",
 links:[["Tao Plus","https://www.taoplus.es/propiedades/vivienda-unifamiliar-0236/"]],
 shots:5},
{id:"h04",tier:4,name:"The Yellow Cottage",ref:"Rep C09537RL",area:"Villanueva de la Cañada, Madrid",
 verdict:"Genuinely beautiful, and the smallest on the list. Realistically it gives us the front of the house and very little beyond it.",
 blocker:"Using it properly needs a crane to clear the roofline.",
 links:[["Rep Locations","https://replocations.com/localizaciones/c09537rl/"]],
 shots:4},
{id:"h09",tier:4,name:"The Canadian",ref:"Tao Plus VU 0200",area:"El Escorial, Madrid",
 verdict:"Wood inside and out, gabled front, wooden porches with railings, and a double-height living room under a mezzanine. Handsome house, sitting just below the top of the list.",
 links:[["Tao Plus","https://www.taoplus.es/propiedades/vivienda-unifamiliar-0200/"]],
 shots:4},
{id:"h10",tier:4,name:"The Picket Fence",ref:"Rep C11372RL",area:"Pozuelo de Alarcón, Madrid",
 verdict:"Suburban American, white picket fence, big open lawn and a covered porch. Reads correctly on camera.",
 blocker:"This location closes at 20:00. On a golden-hour shoot that rules it out.",
 links:[["Rep Locations","https://replocations.com/localizaciones/c11372rl/"]],
 shots:3},
{id:"h08",tier:4,name:"The Estate",ref:"Rep C11569RL",area:"San Agustín del Guadalix, Madrid",
 verdict:"The grandest option by some distance. Stone front with a columned portico, resort-scale pool, large gardens and a separate wooden cabin on the plot. More estate than family house.",
 links:[["Rep Locations","https://replocations.com/localizaciones/c11569rl/"]],
 shots:3},
{id:"h06",tier:4,name:"The Modern",ref:"Tao Plus VU 0447",area:"Madrid, residencial",
 verdict:"Modern and clean, long pool, wooden gazebo with an outdoor kitchen. The safe option if the American houses fall through.",
 links:[["Tao Plus","https://www.taoplus.es/propiedades/vivienda-unifamiliar-0447/"]],
 shots:3},
{id:"h07",tier:4,name:"The Eighties",ref:"Rep C09919RL",area:"Boadilla del Monte, Madrid",
 verdict:"An 80s American chalet with its original furniture and decoration untouched, plus garden, pool and a tennis court. Period rather than contemporary.",
 links:[["Rep Locations","https://replocations.com/localizaciones/c09919rl/"]],
 shots:3},
{id:"h05",tier:4,name:"The Classic",ref:"Tao Plus VU 0213",area:"Boadilla del Monte, Madrid",
 verdict:"The one house here that is not American at all. Classical with an English feel, three floors, billiards room, landscaped plot with a pool. Kept as an option, not as a match.",
 links:[["Tao Plus","https://www.taoplus.es/propiedades/vivienda-unifamiliar-0213/"]],
 shots:3},
];
const TIERS = {
 1:{label:"First choice",  color:"#d99a00"},
 2:{label:"Conditional",   color:"#c6621c"},
 3:{label:"Strong",        color:"#4f9c8b"},
 4:{label:"Option",        color:"#7a828c"},
};
