const HOUSES = [
{id:"h01",tier:1,name:"La Casa Azul",ref:"Tao Plus VU 0451 · Rep C09928RL",area:"El Álamo, Madrid",
 verdict:"Primera opción desde el primer día de scouting. Revestimiento azul americano, hiedra cubriendo todo el frente, porche de lado a lado y piscina con pérgola detrás. Es la única casa de la lista que ya parece el videoclip sin tocarle nada.",
 note:"Está listada por dos agencias distintas. Es la misma casa. Reservar por la que dé mejor precio.",
 links:[["Ver todas las fotos en Tao Plus","https://www.taoplus.es/propiedades/vivienda-unifamiliar-0451/"],["Ficha en Rep Locations","https://replocations.com/localizaciones/c09928rl/"]],
 shots:6},
{id:"h08",tier:2,name:"La Finca",ref:"Rep C11569RL",area:"San Agustín del Guadalix, Madrid",
 verdict:"Candidata seria, y una de las casas más fuertes de toda la lista. Fachada de piedra con pórtico de columnas, piscina de tamaño resort, jardines amplios y una cabaña de madera aparte, que es un segundo escenario dentro de la misma reserva. La llegada más cinematográfica de todas.",
 links:[["Ver todas las fotos en Rep Locations","https://replocations.com/localizaciones/c11569rl/"]],
 shots:9},
{id:"h09",tier:2,name:"La Canadiense",ref:"Tao Plus VU 0200",area:"El Escorial, Madrid",
 verdict:"De lo mejor de la lista y peleando por el primer puesto. Madera por dentro y por fuera, frente a dos aguas, porches de madera con barandilla, camino empedrado bajo robles viejos y un salón a doble altura con altillo. La casa americana más completa después de la azul.",
 links:[["Ver todas las fotos en Tao Plus","https://www.taoplus.es/propiedades/vivienda-unifamiliar-0200/"]],
 shots:4},
{id:"h03",tier:2,name:"La Casa de Madera",ref:"Tao Plus VU 0236",area:"Urb. Santo Domingo, Madrid",
 verdict:"Candidata fuerte. Frente precioso bajo los pinos, y un garaje de madera independiente al otro lado de la parcela que da un segundo escenario real dentro de la misma reserva. Piscina, pérgola y un porche que recorre toda la casa de lado a lado.",
 links:[["Ver todas las fotos en Tao Plus","https://www.taoplus.es/propiedades/vivienda-unifamiliar-0236/"]],
 shots:3},
{id:"h02",tier:3,name:"La Prefabricada",ref:"Rep C10244BRL",area:"Guadarrama, Madrid",
 verdict:"El exterior es la imagen más potente que hemos encontrado en toda la búsqueda. Frente americano de madera, porche y pradera abierta detrás. El problema está dentro: una sola sala abierta y nada más, así que la casa no aguanta un videoclip entero ella sola.",
 blocker:"Dos condiciones antes de que sea viable. El precio del día tiene que ser bajo, y hay que cerrar antes un segundo elemento, una caravana o una camioneta americana. Sin ese segundo elemento no hay material suficiente para rodar.",
 links:[["Ver todas las fotos en Rep Locations","https://replocations.com/localizaciones/c10244brl/"]],
 shots:5},
{id:"h04",tier:4,name:"La Casita Amarilla",ref:"Rep C09537RL",area:"Villanueva de la Cañada, Madrid",
 verdict:"Preciosa de verdad, y la más pequeña de la lista. Siendo realistas da el frente de la casa y poco más.",
 blocker:"Para aprovecharla bien haría falta una grúa que pase por encima del tejado.",
 links:[["Ver todas las fotos en Rep Locations","https://replocations.com/localizaciones/c09537rl/"]],
 shots:4},
{id:"h06",tier:4,name:"La Moderna",ref:"Tao Plus VU 0447",area:"Madrid, zona residencial",
 verdict:"Moderna y limpia, piscina larga, cenador de madera con cocina exterior. La opción segura si las casas americanas se caen.",
 links:[["Ver todas las fotos en Tao Plus","https://www.taoplus.es/propiedades/vivienda-unifamiliar-0447/"]],
 shots:3},
{id:"h07",tier:4,name:"La de los Ochenta",ref:"Rep C09919RL",area:"Boadilla del Monte, Madrid",
 verdict:"Chalet americano de los 80 con el mobiliario y la decoración originales intactos, más jardín, piscina y pista de tenis. De época, no actual.",
 links:[["Ver todas las fotos en Rep Locations","https://replocations.com/localizaciones/c09919rl/"]],
 shots:3},
{id:"h05",tier:4,name:"La Clásica",ref:"Tao Plus VU 0213",area:"Boadilla del Monte, Madrid",
 verdict:"La única casa de aquí que no es americana. Clásica con aire inglés, tres plantas, sala de billar y parcela ajardinada con piscina. Se queda como opción, no como match.",
 links:[["Ver todas las fotos en Tao Plus","https://www.taoplus.es/propiedades/vivienda-unifamiliar-0213/"]],
 shots:3},
];
const TIERS = {
 1:{label:"Primera opción", color:"#8a6600"},
 2:{label:"En la pelea",    color:"#2f7d6b"},
 3:{label:"Con condiciones",color:"#a8500f"},
 4:{label:"Opción",         color:"#5c636d"},
};
